import { PrismaClient, CollegeType } from "@prisma/client";
import * as bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding started...");

  // Clean existing data
  await prisma.userActivity.deleteMany();
  await prisma.comparison.deleteMany();
  await prisma.savedCollege.deleteMany();
  await prisma.college.deleteMany();
  await prisma.user.deleteMany();

  // Create demo user
  const hashedPassword = bcrypt.hashSync("password123", 10);
  const demoUser = await prisma.user.create({
    data: {
      email: "demo@campusiq.com",
      password: hashedPassword,
    },
  });
  console.log(`Created demo user: ${demoUser.email}`);

  // College mock data (26 colleges across multiple states, categories, and exam criteria)
  const collegesData = [
    {
      name: "Indian Institute of Technology Bombay (IITB)",
      location: "Mumbai",
      state: "Maharashtra",
      fees: 220000,
      rating: 4.9,
      placementAvgSalary: 23.5,
      placementHighestSalary: 150.0,
      entranceExam: "JEE",
      cutoffRank: 100,
      established: 1958,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Electrical Engineering", "Mechanical Engineering", "Aerospace Engineering"],
    },
    {
      name: "Indian Institute of Technology Delhi (IITD)",
      location: "New Delhi",
      state: "Delhi",
      fees: 225000,
      rating: 4.8,
      placementAvgSalary: 22.8,
      placementHighestSalary: 140.0,
      entranceExam: "JEE",
      cutoffRank: 115,
      established: 1961,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Chemical Engineering", "Electrical Engineering", "Textile Technology"],
    },
    {
      name: "Indian Institute of Technology Madras (IITM)",
      location: "Chennai",
      state: "Tamil Nadu",
      fees: 210000,
      rating: 4.9,
      placementAvgSalary: 22.0,
      placementHighestSalary: 130.0,
      entranceExam: "JEE",
      cutoffRank: 150,
      established: 1959,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Civil Engineering", "Ocean Engineering", "Metallurgical Engineering"],
    },
    {
      name: "Indian Institute of Technology Kharagpur (IITKGP)",
      location: "Kharagpur",
      state: "West Bengal",
      fees: 215000,
      rating: 4.7,
      placementAvgSalary: 19.5,
      placementHighestSalary: 120.0,
      entranceExam: "JEE",
      cutoffRank: 300,
      established: 1951,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Agricultural Engineering", "Mining Engineering", "Instrumentation Engineering"],
    },
    {
      name: "Indian Institute of Technology Roorkee (IITR)",
      location: "Roorkee",
      state: "Uttarakhand",
      fees: 220000,
      rating: 4.6,
      placementAvgSalary: 18.2,
      placementHighestSalary: 112.0,
      entranceExam: "JEE",
      cutoffRank: 450,
      established: 1847,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Architecture", "Engineering Physics", "Biotechnology"],
    },
    {
      name: "Indian Institute of Technology Guwahati (IITG)",
      location: "Guwahati",
      state: "Assam",
      fees: 220000,
      rating: 4.6,
      placementAvgSalary: 18.0,
      placementHighestSalary: 110.0,
      entranceExam: "JEE",
      cutoffRank: 600,
      established: 1994,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Data Science", "Electronics & Communication Engineering", "Design"],
    },
    {
      name: "National Institute of Technology Trichy (NITT)",
      location: "Tiruchirappalli",
      state: "Tamil Nadu",
      fees: 140000,
      rating: 4.5,
      placementAvgSalary: 15.0,
      placementHighestSalary: 75.0,
      entranceExam: "JEE",
      cutoffRank: 1500,
      established: 1964,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Production Engineering", "Chemical Engineering", "Instrumentation & Control"],
    },
    {
      name: "National Institute of Technology Surathkal (NITK)",
      location: "Surathkal",
      state: "Karnataka",
      fees: 145000,
      rating: 4.4,
      placementAvgSalary: 14.2,
      placementHighestSalary: 68.0,
      entranceExam: "JEE",
      cutoffRank: 2000,
      established: 1960,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Information Technology", "Mining Engineering", "Civil Engineering"],
    },
    {
      name: "National Institute of Technology Warangal (NITW)",
      location: "Warangal",
      state: "Telangana",
      fees: 150000,
      rating: 4.4,
      placementAvgSalary: 14.0,
      placementHighestSalary: 65.0,
      entranceExam: "JEE",
      cutoffRank: 2200,
      established: 1959,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Electronics & Communication", "Biotechnology", "Metallurgical Engineering"],
    },
    {
      name: "International Institute of Information Technology Hyderabad (IIITH)",
      location: "Hyderabad",
      state: "Telangana",
      fees: 360000,
      rating: 4.8,
      placementAvgSalary: 26.0,
      placementHighestSalary: 102.0,
      entranceExam: "JEE",
      cutoffRank: 1200,
      established: 1998,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Electronics & Communication", "Computational Linguistics", "Computational Natural Sciences"],
    },
    {
      name: "International Institute of Information Technology Bangalore (IIITB)",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 320000,
      rating: 4.5,
      placementAvgSalary: 21.0,
      placementHighestSalary: 85.0,
      entranceExam: "JEE",
      cutoffRank: 3000,
      established: 1999,
      type: CollegeType.PRIVATE,
      courses: ["Integrated M.Tech Computer Science", "Integrated M.Tech Electronics", "M.Tech Data Science"],
    },
    {
      name: "International Institute of Information Technology Allahabad (IIITA)",
      location: "Allahabad",
      state: "Uttar Pradesh",
      fees: 180000,
      rating: 4.4,
      placementAvgSalary: 19.0,
      placementHighestSalary: 82.0,
      entranceExam: "JEE",
      cutoffRank: 4000,
      established: 1999,
      type: CollegeType.PUBLIC,
      courses: ["Information Technology", "Electronics & Communication", "IT Business Informatics"],
    },
    {
      name: "BITS Pilani - Pilani Campus",
      location: "Pilani",
      state: "Rajasthan",
      fees: 550000,
      rating: 4.6,
      placementAvgSalary: 18.5,
      placementHighestSalary: 95.0,
      entranceExam: "BITSAT",
      cutoffRank: 320, // BITSAT score is represented here as the metric
      established: 1964,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Chemical Engineering", "Manufacturing Engineering", "M.Sc Physics"],
    },
    {
      name: "BITS Pilani - Goa Campus",
      location: "Zuarinagar",
      state: "Goa",
      fees: 550000,
      rating: 4.4,
      placementAvgSalary: 16.8,
      placementHighestSalary: 88.0,
      entranceExam: "BITSAT",
      cutoffRank: 290,
      established: 2004,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Electronics & Instrumentation", "Mechanical Engineering", "M.Sc Economics"],
    },
    {
      name: "Vellore Institute of Technology (VIT)",
      location: "Vellore",
      state: "Tamil Nadu",
      fees: 198000,
      rating: 4.1,
      placementAvgSalary: 9.0,
      placementHighestSalary: 45.0,
      entranceExam: "VITEEE",
      cutoffRank: 8000,
      established: 1984,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Information Technology", "Biomedical Engineering", "Civil Engineering"],
    },
    {
      name: "SRM Institute of Science and Technology",
      location: "Chennai",
      state: "Tamil Nadu",
      fees: 250000,
      rating: 3.9,
      placementAvgSalary: 7.5,
      placementHighestSalary: 42.0,
      entranceExam: "SRMJEEE",
      cutoffRank: 12000,
      established: 1985,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Aerospace Engineering", "Nanotechnology", "Mechatronics"],
    },
    {
      name: "Manipal Institute of Technology (MIT)",
      location: "Manipal",
      state: "Karnataka",
      fees: 335000,
      rating: 4.2,
      placementAvgSalary: 10.5,
      placementHighestSalary: 50.0,
      entranceExam: "MET",
      cutoffRank: 5000,
      established: 1957,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Aeronautical Engineering", "Data Science & Engineering", "Automobile Engineering"],
    },
    {
      name: "Delhi Technological University (DTU)",
      location: "New Delhi",
      state: "Delhi",
      fees: 219000,
      rating: 4.3,
      placementAvgSalary: 15.2,
      placementHighestSalary: 64.0,
      entranceExam: "JEE",
      cutoffRank: 4500,
      established: 1941,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Software Engineering", "Environmental Engineering", "Engineering Physics"],
    },
    {
      name: "Netaji Subhas University of Technology (NSUT)",
      location: "New Delhi",
      state: "Delhi",
      fees: 219000,
      rating: 4.2,
      placementAvgSalary: 14.8,
      placementHighestSalary: 60.0,
      entranceExam: "JEE",
      cutoffRank: 5000,
      established: 1983,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Information Technology", "Instrumentation & Control", "Manufacturing Processes"],
    },
    {
      name: "College of Engineering Pune (COEP)",
      location: "Pune",
      state: "Maharashtra",
      fees: 135000,
      rating: 4.3,
      placementAvgSalary: 9.8,
      placementHighestSalary: 38.0,
      entranceExam: "MHT-CET",
      cutoffRank: 2500,
      established: 1854,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Metallurgy", "Production Engineering", "Planning"],
    },
    {
      name: "Veermata Jijabai Technological Institute (VJTI)",
      location: "Mumbai",
      state: "Maharashtra",
      fees: 85000,
      rating: 4.2,
      placementAvgSalary: 9.5,
      placementHighestSalary: 36.0,
      entranceExam: "MHT-CET",
      cutoffRank: 1800,
      established: 1887,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Electrical Engineering", "Textile Manufactures", "Civil Engineering"],
    },
    {
      name: "R.V. College of Engineering (RVCE)",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 250000,
      rating: 4.2,
      placementAvgSalary: 11.2,
      placementHighestSalary: 53.0,
      entranceExam: "KCET",
      cutoffRank: 1500,
      established: 1963,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Information Science Engineering", "Electronics & Telecommunication", "Industrial Engineering"],
    },
    {
      name: "PES University",
      location: "Bengaluru",
      state: "Karnataka",
      fees: 380000,
      rating: 4.1,
      placementAvgSalary: 10.0,
      placementHighestSalary: 48.0,
      entranceExam: "KCET",
      cutoffRank: 3500,
      established: 1972,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Electronics & Communication", "Mechanical Engineering", "Biotechnology"],
    },
    {
      name: "Jadavpur University",
      location: "Kolkata",
      state: "West Bengal",
      fees: 10000,
      rating: 4.6,
      placementAvgSalary: 14.5,
      placementHighestSalary: 85.0,
      entranceExam: "WBJEE",
      cutoffRank: 500,
      established: 1955,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Chemical Engineering", "Power Engineering", "Food Technology"],
    },
    {
      name: "PSG College of Technology",
      location: "Coimbatore",
      state: "Tamil Nadu",
      fees: 80000,
      rating: 4.3,
      placementAvgSalary: 8.8,
      placementHighestSalary: 36.0,
      entranceExam: "TNEA",
      cutoffRank: 2000,
      established: 1951,
      type: CollegeType.PUBLIC,
      courses: ["Computer Science Engineering", "Textile Technology", "Metallurgical Engineering", "Bio-Technology"],
    },
    {
      name: "Thapar Institute of Engineering and Technology",
      location: "Patiala",
      state: "Punjab",
      fees: 450000,
      rating: 4.0,
      placementAvgSalary: 8.5,
      placementHighestSalary: 40.0,
      entranceExam: "JEE",
      cutoffRank: 15000,
      established: 1956,
      type: CollegeType.PRIVATE,
      courses: ["Computer Science Engineering", "Mechatronics Engineering", "Electronics & Computers", "Chemical Engineering"],
    },
  ];

  for (const college of collegesData) {
    await prisma.college.create({
      data: college,
    });
  }

  console.log(`Successfully seeded ${collegesData.length} colleges.`);
  console.log("Seeding completed successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
